apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kazoo.secret.name" . }}
  labels:
    {{- include "kazoo.labels" . | nindent 4 }}
type: Opaque
stringData:
  erlangCookie: {{ .Values.secrets.erlangCookie | quote }}
  rabbitUser: {{ .Values.secrets.rabbitUser | quote }}
  rabbitPass: {{ .Values.secrets.rabbitPass | quote }}
  couchUser: {{ .Values.secrets.couchUser | quote }}
  couchPass: {{ .Values.secrets.couchPass | quote }}
  couchSecret: {{ .Values.secrets.couchSecret | quote }}
  postgresUser: {{ .Values.secrets.postgresUser | quote }}
  postgresPass: {{ .Values.secrets.postgresPass | quote }}
  masterAccountName: {{ .Values.secrets.masterAccountName | quote }}
  masterRealm: {{ .Values.secrets.masterRealm | quote }}
  masterUser: {{ .Values.secrets.masterUser | quote }}
  masterPass: {{ .Values.secrets.masterPass | quote }}